### ISSUE TITLE
java.lang.NoSuchFieldError: net/kyori/adventure/identity/Identity.LOCALE

### ISSUE THREAD

**Issue by joshuasing** [HyperaOfficial/Bugs#2]
**Bug description**
When attempting to run UltraStaffChatPro on a legacy server (or proxy) version, Kyori Adventure fails to load.

**How to reproduce**
Steps to reproduce the behaviour:
1. Attempt starting UltraStaffChatPro on a legacy paper server.

**Expected behaviour**
Unless decided otherwise, UltraStaffChatPro should be able to run on legacy servers.

**Screenshots**
N/A

**Platform:**
 - Name: UltraStaffChatPro
 - Version: >= 2.0.0

**Environment:**
 - OS: N/A
 - Server: BungeeCord, Minestom, Spigot, Velocity
 - Server version: Legacy
 - Java version: 16

**Additional context**
Stack-trace:
```
java.lang.NoSuchFieldError: net/kyori/adventure/identity/Identity.LOCALE
  at net.kyori.adventure.platform.bukkit.BukkitAudience.contributePointers(Unknown Source) ~[UltraStaffChatPro-2.0.0.jar:?]
  at net.kyori.adventure.platform.facet.FacetAudience.pointers(Unknown Source) ~[UltraStaffChatPro-2.0.0.jar:?]
```

**Known workarounds**
 - Run a proxy in-front of your server so the plugin is running on up-to-date software without having to update your server version.

**Comment by joshuasing** [comment]
Will be resolved in v2.1.0.
